In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [4]:
#df = pd.read_csv("/Users/nilesh/Downloads/Data Science/Test_Dataset/diabetes.csv")
df = pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/diabetes.csv")

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
arr = df.values

In [7]:
df.Outcome.unique()

array([1, 0])

In [8]:
arr.shape

(768, 9)

In [7]:
#NUMPY will help us for data cleansing

In [9]:
#X = arr[:,0:8]
X = df.drop(['Outcome'],axis = 1)

In [10]:
X.shape

(768, 8)

In [11]:
#Y = arr[:,8]
y = df['Outcome']

In [12]:
y.shape

(768,)

In [13]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [14]:
test = SelectKBest(score_func=chi2, k = 8)
fit = test.fit(X,y)
print(test)
print(fit)

SelectKBest(k=8, score_func=<function chi2 at 0x1a21b75488>)
SelectKBest(k=8, score_func=<function chi2 at 0x1a21b75488>)


In [15]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Speculation','Score_with_y']  #naming the dataframe columns
print(featureScores.nlargest(8,'Score_with_y'))  #print 10 best features

                Speculation  Score_with_y
4                   Insulin   2175.565273
1                   Glucose   1411.887041
7                       Age    181.303689
5                       BMI    127.669343
0               Pregnancies    111.519691
3             SkinThickness     53.108040
2             BloodPressure     17.605373
6  DiabetesPedigreeFunction      5.392682


In [15]:
features = fit.transform(X)

In [16]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [17]:
print(features[0:5,:])

[[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]]


In [18]:
from sklearn.feature_selection import RFE

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model = LinearRegression()

In [21]:
rfe = RFE(model, 4)

In [22]:
x_rfe = rfe.fit_transform(X, y)

In [23]:
DF = pd.DataFrame({"Area":[2600, 3300, 2500, 3000, 4500], 
                          "Bedroom":[3, 4, 3, None, 5],
                  "Age":[5, 10, 1, 3, 6], 
                          "Price": [550000, 610000, 590000, 720000, 
                                   780000]})

In [24]:
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      NaN    3  720000
4  4500      5.0    6  780000

In [25]:
DF.Bedroom.median()

3.5

In [26]:
import math

In [27]:
median_bedroom = math.floor(DF.Bedroom.median())

In [28]:
median_bedroom

3

In [29]:
DF['Bedroom'] = DF['Bedroom'].fillna(median_bedroom)
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      3.0    3  720000
4  4500      5.0    6  780000

In [30]:
reg = LinearRegression()

In [31]:
reg.fit(DF[['Area', 'Bedroom', 'Age']], DF.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
reg.coef_

array([    278.34868887, -159744.86180014,   -5294.11764706])

In [33]:
reg.intercept_

366403.2600992207

In [34]:
reg.predict([[3500, 4, 7]])

array([664585.40042523])

In [35]:
278.349*3500-159744.862*4-5294.118*7+366403.2600992207

664586.4860992207

In [36]:
from sklearn import cross_validation

ImportError: cannot import name 'cross_validation' from 'sklearn' (/anaconda3/lib/python3.7/site-packages/sklearn/__init__.py)

In [ ]:
from sklearn.cross_validation import train_test_split

In [ ]:
data_set = pd.read_csv("/Users/nilesh/Downloads/Data Science/Test_Dataset/diabetes.csv")

In [ ]:
Y = data_set['Outcome']


In [ ]:
X = data_set.drop('Outcome', axis=1)

In [ ]:
X.head()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.25, 
                                                   random_state=20)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
cla = LogisticRegression()

In [ ]:
cla.fit(X_train, y_train)

In [ ]:
y_pred = cla.predict(X_test)

In [ ]:
y_pred

In [ ]:
data_set.describe()

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm1 = confusion_matrix(y_test,y_pred.round())

In [ ]:
print(cm1)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred.round())*100

In [ ]:
url = 'https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/data.csv'
tk = pd.read_csv(url)

In [ ]:
tk.head()