In [1]:
#from sklearn.datasets import load_iris()
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [3]:
#np.random.seed(0)
df = pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/iris.csv")

In [3]:
#CREATE A VAIRABLE for iris dataset
#iris = load_iris()
df.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [4]:
df.shape

(150, 5)

In [5]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [6]:
#DATA PREPN
#df = pd.DataFrame(iris.data, columns=iris.feature_names)
X = df.drop(['species'],axis=1)
X.shape

(150, 4)

In [7]:
y = df[['species']]
len(y)
#y['species'],_ = pd.factorize(y['species'])
#view target
y['species'],_ = pd.factorize(y['species'])

<ipython-input-7-c96e1ec63391>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['species'],_ = pd.factorize(y['species'])


In [8]:
from sklearn.model_selection import train_test_split
#Adding a new column for species name
#df['species'] = pd.DataFrame.(iris.target,iris.target_names)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.26,
                                                   random_state=0)
#Creating test and train data
#df['is_train'] = np.random.uniform(0,1,len(df)) <= .75
#view the top 5 rows

In [8]:
#Creating dataframe with testing row and training row
#train, test = df[df['is_train']==True], df[df['is_train']==False]

In [10]:
#Show the number of observation for training and testing dataset
print("training dataset : ", len(X_train))
print("testing dataset : ", len(X_test))
print("training dataset : ", len(y_train))
print("training dataset : ", len(y_test))

training dataset :  111
testing dataset :  39
training dataset :  111
training dataset :  39


In [10]:
#create list of feature column name:
#features = df.columns[:4]
#view features
#features

In [11]:
#converting each species name into digits


In [11]:
#Creating a random forest classifier
clf = RandomForestClassifier(n_estimators=3,n_jobs=-1,random_state=0)
#training the classifier
clf.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=-1,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [12]:
y_pred = clf.predict(X_test)

In [50]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2

In [13]:
clf.predict([[5.0,3.4,1.5,0.2]])

array([0])

In [16]:
len(y_test)

38

In [17]:
len(y_pred)

38

In [14]:
#applying the trained classifier to the test
clf.score(X_test,y_test)*100

97.43589743589743

In [19]:
y_test

species
114        2
62         1
33         0
107        2
7          0
100        2
40         0
86         1
76         1
71         1
134        2
51         1
73         1
54         1
63         1
37         0
78         1
90         1
45         0
16         0
121        2
66         1
24         0
8          0
126        2
22         0
44         0
97         1
93         1
26         0
137        2
84         1
27         0
127        2
132        2
59         1
18         0
83         1

In [20]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [21]:
clf.predict([[6.0,2.7,5.1,1.6]])
#view predicted probability of first 10 observations
#clf.predict_proba(test[features])[0:10]

array([2])

In [22]:
#mapping names for the plants for each predicted plant class
#preds = iris.target_names[clf.predict(test[features])]

In [23]:
#preds[0:20]

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
as1 = accuracy_score(y_test['species'], y_pred)

In [27]:
print(as1)

0.9736842105263158
